What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

Numpy Arrays Vs Python Sequences

NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [3]:
pip install numpy

  Using cached numpy-2.3.5-cp313-cp313-win_amd64.whl.metadata (60 kB)
Using cached numpy-2.3.5-cp313-cp313-win_amd64.whl (12.8 MB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
b =np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
c =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [5]:
np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [6]:
np.arange(1,11,2)


array([1, 3, 5, 7, 9])

In [7]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.zeros((2,3))  # 2 rows, 3 columns of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.random.random((2,3))  # 2 rows, 3 columns of random numbers between 0 and 1

array([[0.08651551, 0.58645731, 0.72939659],
       [0.97481054, 0.76839233, 0.16717541]])

In [12]:
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes

In [14]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
a3.ndim


3

In [16]:
print(a3.shape)
a3  # prints the shape of the array

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [18]:
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [19]:
a3.itemsize

8

In [20]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


Changing Datatype

In [21]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array operations

In [22]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [23]:
# Sclar Operations
#arithematic
a1 ** 2


array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [24]:
a1 == 15

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [25]:
# vector operations 
#arithimetic

a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

Array functions

In [4]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[52., 98., 67.],
       [68., 11., 67.],
       [33., 18., 80.]])

In [7]:
#max/min/sum/prod
# 0 -> col and 1 -> row

np.prod(a1,axis =0)


array([116688.,  19404., 359120.])

In [9]:
#max/median/std/var
np.var(a1,axis=1)

array([366.88888889, 709.55555556, 697.55555556])

In [10]:
np.sin(a1)

array([[ 0.98662759, -0.57338187, -0.85551998],
       [-0.89792768, -0.99999021, -0.85551998],
       [ 0.99991186, -0.75098725, -0.99388865]])

In [11]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [12]:
np.exp(a1)


array([[3.83100800e+22, 3.63797095e+42, 1.25236317e+29],
       [3.40427605e+29, 5.98741417e+04, 1.25236317e+29],
       [2.14643580e+14, 6.56599691e+07, 5.54062238e+34]])

In [13]:
#round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[ 83.,   4.,  40.],
       [ 69.,  67., 100.]])

Indexing and slicing

In [14]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
a2[1,2]

np.int64(6)

In [18]:
a3[1,0,1]

np.int64(5)

In [19]:
a3[1,1,0]

np.int64(6)

In [20]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a1[2:5:2]

array([2, 4])

In [22]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [24]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [25]:
a2[1,::3]

array([4, 7])

In [26]:
a2[0,:]

array([0, 1, 2, 3])

In [27]:
a2[:,2]

array([ 2,  6, 10])

In [28]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [29]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [32]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [31]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [33]:
a3[1,1,:]

array([12, 13, 14])

Iterating

In [34]:
a1

for i in a1:
 print(i)

0
1
2
3
4
5
6
7
8
9


In [35]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [40]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [41]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [42]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Reshaping

In [43]:
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [44]:
#ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Stacking

In [45]:
#horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [46]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [47]:
#vertical stacking

np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting

In [48]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
np.hsplit(a4,5)

ValueError: array split does not result in an equal division

In [50]:
# vertical spliting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [51]:
np.vsplit(a5,2)

ValueError: array split does not result in an equal division