np.sort

Return a sort copy of an array

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
import numpy as np 
a = np.random.randint(1,100,15)
a

array([31, 20, 76, 32, 48, 54, 58, 73,  9, 17, 70, 96, 27, 40, 96],
      dtype=int32)

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[71, 69, 32, 37],
       [77, 10, 31, 27],
       [32, 46, 50, 89],
       [42, 58, 42, 25],
       [27,  9,  8, 72],
       [70,  2, 30, 13]], dtype=int32)

In [5]:
np.sort(a)[::-1]  # Sort array a in descending order

array([96, 96, 76, 73, 70, 58, 54, 48, 40, 32, 31, 27, 20, 17,  9],
      dtype=int32)

In [6]:
np .sort(b, axis=0)  # Sort each column of array b

array([[27,  2,  8, 13],
       [32,  9, 30, 25],
       [42, 10, 31, 27],
       [70, 46, 32, 37],
       [71, 58, 42, 72],
       [77, 69, 50, 89]], dtype=int32)

np.append

The numpy.append() appends values along the mentioned axis at the end of the array 

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [7]:
np.append(a,200)

array([ 31,  20,  76,  32,  48,  54,  58,  73,   9,  17,  70,  96,  27,
        40,  96, 200])

In [8]:
b

array([[71, 69, 32, 37],
       [77, 10, 31, 27],
       [32, 46, 50, 89],
       [42, 58, 42, 25],
       [27,  9,  8, 72],
       [70,  2, 30, 13]], dtype=int32)

In [9]:
np.append (b,np.random.random((b.shape[0],1)),axis=1)

array([[7.10000000e+01, 6.90000000e+01, 3.20000000e+01, 3.70000000e+01,
        6.52582358e-01],
       [7.70000000e+01, 1.00000000e+01, 3.10000000e+01, 2.70000000e+01,
        3.01203897e-02],
       [3.20000000e+01, 4.60000000e+01, 5.00000000e+01, 8.90000000e+01,
        2.96268373e-01],
       [4.20000000e+01, 5.80000000e+01, 4.20000000e+01, 2.50000000e+01,
        2.98443490e-02],
       [2.70000000e+01, 9.00000000e+00, 8.00000000e+00, 7.20000000e+01,
        7.56598679e-01],
       [7.00000000e+01, 2.00000000e+00, 3.00000000e+01, 1.30000000e+01,
        6.74310720e-01]])

np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html


In [10]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [11]:
np.concatenate((c,d),axis=0)  # Concatenate along rows (vertical stacking)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
np.concatenate((c,d),axis=1)  # Concatenate along columns (horizontal stacking)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

np.unique

With the help of np.unique(),we can get the unique values fron an array given as parameter in np.unique()method

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/


In [13]:
e = np.array([1,1,2,2,3,3,4,45,5,6,6])

In [14]:
np.unique(e)

array([ 1,  2,  3,  4,  5,  6, 45])

np.expand_dims

With the help of Numpy.expand_dims()method, we can get the expand dimentions of and array 

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html


In [15]:
a.shape

(15,)

In [17]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [18]:
np.expand_dims(a,axis=1)

array([[31],
       [20],
       [76],
       [32],
       [48],
       [54],
       [58],
       [73],
       [ 9],
       [17],
       [70],
       [96],
       [27],
       [40],
       [96]], dtype=int32)

np.where 

the NUmpy.where() function returns the indices of the elements in an input array where the ggiven condition is satisfied

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [19]:
a

array([31, 20, 76, 32, 48, 54, 58, 73,  9, 17, 70, 96, 27, 40, 96],
      dtype=int32)

In [20]:
np.where (a>50)

(array([ 2,  5,  6,  7, 10, 11, 14]),)

In [21]:
np.where(a>50,0,a)

array([31, 20,  0, 32, 48,  0,  0,  0,  9, 17,  0,  0, 27, 40,  0],
      dtype=int32)

In [22]:
np.where(a%2==0,0,a)

array([31,  0,  0,  0,  0,  0,  0, 73,  9, 17,  0,  0, 27,  0,  0],
      dtype=int32)

np..argmax

The numpy.argmax() function retunrs indinces of the max element of the araay of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [23]:
a

array([31, 20, 76, 32, 48, 54, 58, 73,  9, 17, 70, 96, 27, 40, 96],
      dtype=int32)

In [24]:
np.argmax(a)

np.int64(11)

In [25]:
b

array([[71, 69, 32, 37],
       [77, 10, 31, 27],
       [32, 46, 50, 89],
       [42, 58, 42, 25],
       [27,  9,  8, 72],
       [70,  2, 30, 13]], dtype=int32)

In [26]:
np.argmax(b,axis=0)

array([1, 0, 2, 2])

In [27]:
np.argmax(b,axis=1)

array([0, 0, 3, 1, 3, 0])

In [28]:
np.argmin(a)

np.int64(8)

np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [29]:
a

array([31, 20, 76, 32, 48, 54, 58, 73,  9, 17, 70, 96, 27, 40, 96],
      dtype=int32)

In [30]:
np.cumsum(a)

array([ 31,  51, 127, 159, 207, 261, 319, 392, 401, 418, 488, 584, 611,
       651, 747])

In [31]:
b

array([[71, 69, 32, 37],
       [77, 10, 31, 27],
       [32, 46, 50, 89],
       [42, 58, 42, 25],
       [27,  9,  8, 72],
       [70,  2, 30, 13]], dtype=int32)

In [33]:
np.cumsum(b,axis=1)

array([[ 71, 140, 172, 209],
       [ 77,  87, 118, 145],
       [ 32,  78, 128, 217],
       [ 42, 100, 142, 167],
       [ 27,  36,  44, 116],
       [ 70,  72, 102, 115]])

In [35]:
np.cumsum(b)

array([ 71, 140, 172, 209, 286, 296, 327, 354, 386, 432, 482, 571, 613,
       671, 713, 738, 765, 774, 782, 854, 924, 926, 956, 969])

In [36]:
np.cumprod(a)

array([                  31,                  620,                47120,
                    1507840,             72376320,           3908321280,
               226682634240,       16547832299520,      148930490695680,
           2531818341826560,   177227283927859200, -1432924816635068416,
       -1795481901727744000,  1967700225728446464,  4431780932835344384])

np.percentile 

numpy.percentile() function used to compute the nth
percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [37]:
a

array([31, 20, 76, 32, 48, 54, 58, 73,  9, 17, 70, 96, 27, 40, 96],
      dtype=int32)

In [38]:
np.percentile(a,50)

np.float64(48.0)

In [39]:
np.median(a)

np.float64(48.0)

np.histogram

Numpy has a built-in numpy.histogram() function which reprents the frequency of the data distribution in the graphical form

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [40]:
a

array([31, 20, 76, 32, 48, 54, 58, 73,  9, 17, 70, 96, 27, 40, 96],
      dtype=int32)

In [41]:
np.histogram(a,bins=[0,50,100])

(array([8, 7]), array([  0,  50, 100]))

np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [42]:
salary = np.array([1000,2000,3000,4000,5000,6000,7000,8000,9000,10000])
experience = np.array([1,2,3,4,5,6,7,8,9,10])

np.corrcoef(salary,experience)

array([[1., 1.],
       [1., 1.]])

np.isin

With the help of numpy.isin() method, we can see the one array having values are chaecked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [43]:
a

array([31, 20, 76, 32, 48, 54, 58, 73,  9, 17, 70, 96, 27, 40, 96],
      dtype=int32)

In [44]:
items = [10,20,30,40,50,60,70,80,90,100]
a[np.isin(a,items)]

array([20, 70, 40], dtype=int32)

np.flip 

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [45]:
a

array([31, 20, 76, 32, 48, 54, 58, 73,  9, 17, 70, 96, 27, 40, 96],
      dtype=int32)

In [46]:
np.flip(a)

array([96, 40, 27, 96, 70, 17,  9, 73, 58, 54, 48, 32, 76, 20, 31],
      dtype=int32)

In [47]:
b

array([[71, 69, 32, 37],
       [77, 10, 31, 27],
       [32, 46, 50, 89],
       [42, 58, 42, 25],
       [27,  9,  8, 72],
       [70,  2, 30, 13]], dtype=int32)

In [48]:
np.flip(b,axis=1)

array([[37, 32, 69, 71],
       [27, 31, 10, 77],
       [89, 50, 46, 32],
       [25, 42, 58, 42],
       [72,  8,  9, 27],
       [13, 30,  2, 70]], dtype=int32)

np.put

The numpy.put () function replaces specific elements of an array with given values of p_array.Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [51]:
a

array([110, 530,  76,  32,  48,  54,  58,  73,   9,  17,  70,  96,  27,
        40,  96], dtype=int32)

In [50]:
np.put(a,[0,1],[110,530])

np.delete

The numpy.delete() function retunrs a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [52]:
a

array([110, 530,  76,  32,  48,  54,  58,  73,   9,  17,  70,  96,  27,
        40,  96], dtype=int32)

In [53]:
np.delete(a,[0,2,4])

array([530,  32,  54,  58,  73,   9,  17,  70,  96,  27,  40,  96],
      dtype=int32)

Set functions

Np.union1d
np.intersect1d
np.setdiff1d
np.setxor1d
np.in1d

In [54]:
m = np.array([1,2,3,4,5])
n = np.array([6,7,8,9,10])

np.union1d(m,n)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
np.intersect1d(m,n)


array([], dtype=int64)

In [56]:
np.setdiff1d(m,n)

array([1, 2, 3, 4, 5])

In [57]:
np.setxor1d(m,n)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
m[np.in1d(m,1)]

C:\Users\hp\AppData\Local\Temp\ipykernel_22456\524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

np.clip

numpy.clip() function is used to clip (limit) the values in an array 

https://numpy.org/doc/stable/reference/generated/numpy.clip.html


In [59]:
a

array([110, 530,  76,  32,  48,  54,  58,  73,   9,  17,  70,  96,  27,
        40,  96], dtype=int32)

In [60]:
np.clip(a,a_min=30,a_max=70)

array([70, 70, 70, 32, 48, 54, 58, 70, 30, 30, 70, 70, 30, 40, 70],
      dtype=int32)